apiVersion: v1
kind: Pod

metadata:
  name: telemetry-pod

spec:
  containers:
    - name: telemetry-container
      image: telemetry-services
      imagePullPolicy: Never

      ports:
        - containerPort: 3000